"""
test_troubleshooting_orchestrator.py
──────────────────────────────────────────────────────────────────────────────
Comprehensive unit tests for the Enterprise Troubleshooting Orchestrator.

Test strategy
--------------
• Zero real LLM calls — ai_provider is always mocked.
• No database connections — state is in-memory.
• No external network dependencies.
• All ReasoningEngine calls use deterministic mock responses.
• Tests validate:
    - Conversation flows (VPN, Outlook, Printer, SAP, Password, Wi-Fi, Hardware)
    - State persistence across turns
    - Step non-repetition
    - Knowledge retrieval ranking
    - DecisionSchema validation and fallback
    - Reasoning producing structured output only (no response text)
    - Final response generated by ai_provider.chat(), not reasoning
    - Resolution detection
    - Escalation with full session context passed to TicketService
    - Strategy selection by domain
    - GENERAL fallback strategy

Usage
------
    python -m pytest tests/test_troubleshooting_orchestrator.py -v
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from unittest.mock import MagicMock, patch, PropertyMock

import pytest


# ── Lightweight mock for ITSMClassification ───────────────────────────────────

@dataclass
class MockClassification:
    category: str = "VPN"
    subcategory: str = "Connection Issue"
    assignment_group: str = "Network Team"
    confidence: float = 0.92
    issue_type: str = "INCIDENT"


# ── Mock AIProvider ───────────────────────────────────────────────────────────

def _make_valid_decision(
    next_action: str = "ASK_QUESTION",
    confidence: float = 0.85,
    missing_information: Optional[List[str]] = None,
    selected_kb: str = "",
    selected_step: str = "",
    escalation: bool = False,
    reason_code: str = "MISSING_EVIDENCE",
    requires_confirmation: bool = False,
) -> str:
    """Return a valid JSON decision string matching DECISION_SCHEMA."""
    return json.dumps({
        "next_action":           next_action,
        "confidence":            confidence,
        "missing_information":   missing_information or [],
        "selected_kb":           selected_kb,
        "selected_step":         selected_step,
        "escalation":            escalation,
        "reason_code":           reason_code,
        "requires_confirmation": requires_confirmation,
    })


def _make_mock_ai_provider(
    decision_json: Optional[str] = None,
    chat_response: str = "Let me help you troubleshoot that. Could you tell me what error code you see?",
):
    """
    Create a MagicMock AIProvider that:
    - generate_response() returns a valid DECISION_SCHEMA JSON string
    - chat() returns a natural language response string
    """
    provider = MagicMock()
    provider.is_ready.return_value = True

    # generate_response returns the decision JSON
    gen_response = MagicMock()
    gen_response.text = decision_json or _make_valid_decision()
    provider.generate_response.return_value = gen_response

    # chat returns the natural language string directly
    provider.chat.return_value = chat_response

    return provider


# ── Shared Factory ────────────────────────────────────────────────────────────

def _build_orchestrator(
    ai_provider=None,
    ticket_service=None,
):
    """Build a fully wired TroubleshootingOrchestrator with real sub-services."""
    from app.services.knowledge_retrieval_service import KnowledgeRetrievalService
    from app.services.troubleshooting_strategy import TroubleshootingStrategyRegistry
    from app.services.context_builder import ContextBuilder
    from app.services.reasoning_service import ReasoningEngine
    from app.services.troubleshooting_state_service import TroubleshootingStateManager
    from app.services.troubleshooting_orchestrator import TroubleshootingOrchestrator

    if ai_provider is None:
        ai_provider = _make_mock_ai_provider()

    knowledge_svc  = KnowledgeRetrievalService()
    strategy_reg   = TroubleshootingStrategyRegistry()
    context_bld    = ContextBuilder()
    state_mgr      = TroubleshootingStateManager()
    reasoning_eng  = ReasoningEngine(ai_provider=ai_provider, context_builder=context_bld)

    return TroubleshootingOrchestrator(
        knowledge_service=knowledge_svc,
        strategy_registry=strategy_reg,
        context_builder=context_bld,
        reasoning_engine=reasoning_eng,
        state_manager=state_mgr,
        ai_provider=ai_provider,
        ticket_service=ticket_service,
    )


def _make_request(
    session_id: Optional[str] = None,
    user_message: str = "My VPN is not connecting",
    category: str = "VPN",
    history: Optional[List[dict]] = None,
) -> "OrchestrationRequest":
    from app.services.troubleshooting_orchestrator import OrchestrationRequest
    return OrchestrationRequest(
        session_id=session_id or str(uuid.uuid4()),
        user_message=user_message,
        classification=MockClassification(category=category),
        conversation_history=history or [],
    )


# ═════════════════════════════════════════════════════════════════════════════
# 1. IMPORT INTEGRITY
# ═════════════════════════════════════════════════════════════════════════════

class TestImportIntegrity:
    """All six new services must be importable independently."""

    def test_import_knowledge_retrieval_service(self):
        from app.services.knowledge_retrieval_service import (
            KnowledgeRetrievalService, RetrievedDocument
        )
        assert KnowledgeRetrievalService is not None
        assert RetrievedDocument is not None

    def test_import_troubleshooting_strategy(self):
        from app.services.troubleshooting_strategy import (
            TroubleshootingStrategy, TroubleshootingStrategyRegistry
        )
        assert TroubleshootingStrategy is not None
        assert TroubleshootingStrategyRegistry is not None

    def test_import_context_builder(self):
        from app.services.context_builder import (
            ContextBuilder, ReasoningContext, ResponseContext
        )
        assert ContextBuilder is not None

    def test_import_reasoning_service(self):
        from app.services.reasoning_service import (
            ReasoningEngine, ReasoningResult, NextAction, DECISION_SCHEMA
        )
        assert ReasoningEngine is not None
        assert DECISION_SCHEMA is not None

    def test_import_troubleshooting_state_service(self):
        from app.services.troubleshooting_state_service import (
            TroubleshootingStateManager, TroubleshootingState,
            TroubleshootingStep, ResolutionStatus
        )
        assert TroubleshootingStateManager is not None

    def test_import_troubleshooting_orchestrator(self):
        from app.services.troubleshooting_orchestrator import (
            TroubleshootingOrchestrator, OrchestrationRequest, OrchestrationResult,
            PolicyDecision
        )
        assert TroubleshootingOrchestrator is not None

    def test_policy_decision_stub_defaults(self):
        from app.services.troubleshooting_orchestrator import PolicyDecision
        p = PolicyDecision()
        assert p.requires_admin is False
        assert p.requires_approval is False


# ═════════════════════════════════════════════════════════════════════════════
# 2. TROUBLESHOOTING STRATEGY
# ═════════════════════════════════════════════════════════════════════════════

class TestTroubleshootingStrategy:
    """Validate all built-in strategies and registry behaviour."""

    def setup_method(self):
        from app.services.troubleshooting_strategy import TroubleshootingStrategyRegistry
        self.registry = TroubleshootingStrategyRegistry()

    def test_vpn_strategy_exists(self):
        s = self.registry.get("VPN")
        assert s.domain == "VPN"
        assert len(s.required_evidence) > 0
        assert len(s.escalation_criteria) > 0

    def test_vpn_strategy_required_evidence_includes_error_code(self):
        s = self.registry.get("VPN")
        combined = " ".join(s.required_evidence).lower()
        assert "error" in combined

    def test_printer_strategy_required_evidence_includes_queue(self):
        s = self.registry.get("PRINTER")
        combined = " ".join(s.required_evidence).lower()
        assert "queue" in combined or "driver" in combined

    def test_outlook_strategy_exists(self):
        s = self.registry.get("OUTLOOK")
        assert s.domain == "OUTLOOK"
        assert len(s.required_evidence) > 0

    def test_sap_strategy_escalation_criteria(self):
        s = self.registry.get("SAP")
        combined = " ".join(s.escalation_criteria).lower()
        assert "basis" in combined or "admin" in combined

    def test_password_strategy_alias(self):
        """PASSWORD_RESET alias should resolve to the PASSWORD strategy."""
        s = self.registry.get("PASSWORD_RESET")
        assert s.domain == "PASSWORD"

    def test_wifi_alias_resolves_to_network(self):
        s = self.registry.get("GUEST_WIFI")
        assert s.domain == "NETWORK"

    def test_device_health_alias_resolves_to_hardware(self):
        s = self.registry.get("DEVICE_HEALTH")
        assert s.domain == "HARDWARE"

    def test_unknown_domain_returns_general_fallback(self):
        s = self.registry.get("COMPLETELY_UNKNOWN_CATEGORY_XYZ")
        assert s.domain == "GENERAL"

    def test_all_strategies_have_stopping_conditions(self):
        for domain in self.registry.list_domains():
            s = self.registry.get(domain)
            assert len(s.stopping_conditions) > 0, f"{domain} has no stopping conditions"

    def test_all_strategies_have_escalation_criteria(self):
        for domain in self.registry.list_domains():
            s = self.registry.get(domain)
            assert len(s.escalation_criteria) > 0, f"{domain} has no escalation criteria"


# ═════════════════════════════════════════════════════════════════════════════
# 3. KNOWLEDGE RETRIEVAL SERVICE
# ═════════════════════════════════════════════════════════════════════════════

class TestKnowledgeRetrievalService:
    """Validate retrieve(), ranking, and future-hook stubs."""

    def setup_method(self):
        from app.services.knowledge_retrieval_service import KnowledgeRetrievalService
        self.service = KnowledgeRetrievalService()

    def test_retrieve_empty_query_returns_empty(self):
        result = self.service.retrieve("")
        assert result == []

    def test_retrieve_whitespace_only_returns_empty(self):
        result = self.service.retrieve("   ")
        assert result == []

    def test_retrieve_returns_list(self):
        result = self.service.retrieve("VPN GlobalProtect not connecting")
        assert isinstance(result, list)

    def test_retrieved_docs_sorted_by_confidence_descending(self):
        result = self.service.retrieve("VPN disconnects", max_results=3)
        confidences = [doc.confidence for doc in result]
        assert confidences == sorted(confidences, reverse=True)

    def test_retrieved_docs_have_rank_starting_at_1(self):
        result = self.service.retrieve("Outlook not opening", max_results=2)
        if result:
            assert result[0].rank == 1

    def test_min_confidence_filter(self):
        """All returned docs should meet min_confidence threshold."""
        result = self.service.retrieve("printer", min_confidence=0.50)
        for doc in result:
            assert doc.confidence >= 0.50

    def test_content_summary_not_empty_when_article_found(self):
        result = self.service.retrieve("VPN GlobalProtect", max_results=1)
        for doc in result:
            assert doc.content_summary, "content_summary must not be empty"

    def test_content_summary_does_not_contain_raw_steps(self):
        """content_summary should be a digest, not a list of step instructions."""
        result = self.service.retrieve("VPN", max_results=1)
        for doc in result:
            # content_summary must be short — raw article dumps would be huge
            assert len(doc.content_summary) < 600, "content_summary appears to contain raw article dump"

    def test_rerank_passthrough_in_phase1(self):
        result = self.service.retrieve("VPN", max_results=2)
        reranked = self.service.rerank(result, "VPN GlobalProtect error")
        assert reranked == result  # pass-through in Phase 1

    def test_deduplicate_removes_duplicate_ids(self):
        from app.services.knowledge_retrieval_service import RetrievedDocument
        doc1 = RetrievedDocument("KB0001", "VPN", "VPN", "summary", [], {}, 0.9, [], 1)
        doc2 = RetrievedDocument("KB0001", "VPN", "VPN", "summary", [], {}, 0.8, [], 2)  # duplicate
        doc3 = RetrievedDocument("KB0002", "Outlook", "OUTLOOK", "summary2", [], {}, 0.7, [], 3)
        result = self.service.deduplicate([doc1, doc2, doc3])
        ids = [d.article_id for d in result]
        assert len(ids) == len(set(ids)), "deduplicate must remove duplicate article_ids"

    def test_hybrid_search_falls_back_to_retrieve(self):
        result = self.service.hybrid_search("VPN error", max_results=2)
        assert isinstance(result, list)


# ═════════════════════════════════════════════════════════════════════════════
# 4. TROUBLESHOOTING STATE MANAGER
# ═════════════════════════════════════════════════════════════════════════════

class TestTroubleshootingStateManager:
    """Validate state lifecycle, step recording, and answer tracking."""

    def setup_method(self):
        from app.services.troubleshooting_state_service import (
            TroubleshootingStateManager, ResolutionStatus
        )
        self.mgr = TroubleshootingStateManager()
        self.ResolutionStatus = ResolutionStatus

    def _sid(self):
        return str(uuid.uuid4())

    def test_create_returns_state(self):
        sid = self._sid()
        state = self.mgr.create(sid, "VPN not connecting", "VPN")
        assert state.session_id == sid
        assert state.current_issue == "VPN not connecting"

    def test_create_idempotent(self):
        sid = self._sid()
        s1 = self.mgr.create(sid, "Issue", "VPN")
        s2 = self.mgr.create(sid, "Other issue", "OUTLOOK")
        assert s1.session_id == s2.session_id
        assert s2.current_issue == "Issue"  # original preserved

    def test_get_returns_none_for_unknown_session(self):
        assert self.mgr.get("nonexistent-session") is None

    def test_get_returns_state_after_create(self):
        sid = self._sid()
        self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.get(sid)
        assert state is not None

    def test_increment_turn(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        assert state.turn_count == 0
        state = self.mgr.increment_turn(state)
        assert state.turn_count == 1
        state = self.mgr.increment_turn(state)
        assert state.turn_count == 2

    def test_record_step_adds_to_completed(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_step(state, "Restart VPN client", success=True)
        assert len(state.completed_steps) == 1
        assert state.completed_steps[0].instruction == "Restart VPN client"

    def test_record_step_failure_adds_to_failed(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_step(state, "Reinstall VPN", success=False)
        assert len(state.failed_steps) == 1
        assert len(state.completed_steps) == 0

    def test_has_attempted_returns_true_for_recorded_step(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_step(state, "Restart VPN client")
        assert self.mgr.has_attempted(state, "Restart VPN client") is True

    def test_has_attempted_returns_false_for_unrecorded_step(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        assert self.mgr.has_attempted(state, "Reinstall GlobalProtect") is False

    def test_has_attempted_case_insensitive(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_step(state, "Restart VPN client")
        assert self.mgr.has_attempted(state, "RESTART VPN CLIENT") is True

    def test_record_user_answer(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_user_answer(state, "What error code?", "Error 619")
        assert "What error code?" in state.user_answers
        assert state.user_answers["What error code?"] == "Error 619"

    def test_record_user_answer_extracts_error_code(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.record_user_answer(state, "What error code?", "Error 619")
        assert "619" in state.error_codes or "Error 619" in " ".join(state.error_codes)

    def test_mark_resolved(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.mark_resolved(state)
        assert state.resolution_status == self.ResolutionStatus.RESOLVED

    def test_mark_escalated(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state = self.mgr.mark_escalated(state)
        assert state.resolution_status == self.ResolutionStatus.ESCALATED

    def test_state_to_summary_not_empty(self):
        sid = self._sid()
        state = self.mgr.create(sid, "VPN not connecting", "VPN")
        summary = state.to_summary()
        assert "VPN" in summary
        assert len(summary) > 0

    def test_update_persists_state(self):
        sid = self._sid()
        state = self.mgr.create(sid, "Issue", "VPN")
        state.turn_count = 5
        self.mgr.update(sid, state)
        retrieved = self.mgr.get(sid)
        assert retrieved.turn_count == 5


# ═════════════════════════════════════════════════════════════════════════════
# 5. CONTEXT BUILDER
# ═════════════════════════════════════════════════════════════════════════════

class TestContextBuilder:
    """Validate context assembly, history trimming, and KB summary generation."""

    def setup_method(self):
        from app.services.context_builder import ContextBuilder
        from app.services.troubleshooting_strategy import TroubleshootingStrategyRegistry
        from app.services.troubleshooting_state_service import TroubleshootingStateManager
        self.builder = ContextBuilder()
        self.strategy_reg = TroubleshootingStrategyRegistry()
        self.state_mgr = TroubleshootingStateManager()

    def _make_state(self, category="VPN"):
        sid = str(uuid.uuid4())
        return self.state_mgr.create(sid, "VPN not working", category)

    def _make_docs(self, n=2):
        from app.services.knowledge_retrieval_service import RetrievedDocument
        return [
            RetrievedDocument(
                article_id=f"KB000{i}",
                title=f"Article {i}",
                category="VPN",
                content_summary=f"Problem summary {i}",
                troubleshooting_steps=[{"title": f"Step {i}.1"}, {"title": f"Step {i}.2"}],
                escalation_info={"contact": "IT Support"},
                confidence=0.9 - i * 0.1,
                matched_keywords=["vpn"],
                rank=i,
            )
            for i in range(1, n + 1)
        ]

    def test_build_reasoning_context_returns_correct_type(self):
        from app.services.context_builder import ReasoningContext
        state = self._make_state()
        ctx = self.builder.build_reasoning_context(
            user_message="VPN not connecting",
            classification=MockClassification(category="VPN"),
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=self._make_docs(),
            state=state,
            history=[],
        )
        assert isinstance(ctx, ReasoningContext)
        assert ctx.category == "VPN"

    def test_history_trimmed_to_max_history_turns(self):
        state = self._make_state()
        long_history = [{"role": "user", "text": f"msg {i}"} for i in range(20)]
        ctx = self.builder.build_reasoning_context(
            user_message="VPN",
            classification=MockClassification(),
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=[],
            state=state,
            history=long_history,
        )
        assert len(ctx.conversation_history) <= self.builder.MAX_HISTORY_TURNS

    def test_build_response_context_returns_correct_type(self):
        from app.services.context_builder import ResponseContext
        from app.services.reasoning_service import ReasoningResult, NextAction
        state = self._make_state()
        result = ReasoningResult(
            next_action=NextAction.ASK_QUESTION,
            confidence=0.8,
            missing_information=["error code"],
            selected_kb="",
            selected_step="",
            escalation=False,
            reason_code="MISSING_EVIDENCE",
            requires_confirmation=False,
            raw_reasoning="...",
            is_fallback=False,
        )
        ctx = self.builder.build_response_context(
            reasoning_result=result,
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=self._make_docs(),
            state=state,
            history=[],
        )
        assert isinstance(ctx, ResponseContext)

    def test_kb_context_in_response_does_not_contain_article_id(self):
        """KB context for response prompt must contain summaries only, not IDs."""
        from app.services.reasoning_service import ReasoningResult, NextAction
        state = self._make_state()
        docs = self._make_docs()
        result = ReasoningResult(
            next_action=NextAction.GUIDE_STEP,
            confidence=0.9,
            missing_information=[],
            selected_kb="KB0001",
            selected_step="Check VPN client version",
            escalation=False,
            reason_code="KB_AVAILABLE",
            requires_confirmation=False,
            raw_reasoning="",
            is_fallback=False,
        )
        response_ctx = self.builder.build_response_context(
            reasoning_result=result,
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=docs,
            state=state,
            history=[],
        )
        # The kb_context for response should contain summaries only
        # (not expose article IDs in a way that would be shown to users)
        assert isinstance(response_ctx.kb_context, str)

    def test_build_response_prompt_contains_critical_rules(self):
        from app.services.reasoning_service import ReasoningResult, NextAction
        state = self._make_state()
        result = ReasoningResult(
            next_action=NextAction.ASK_QUESTION,
            confidence=0.8,
            missing_information=[],
            selected_kb="",
            selected_step="",
            escalation=False,
            reason_code="MISSING_EVIDENCE",
            requires_confirmation=False,
            raw_reasoning="",
            is_fallback=False,
        )
        response_ctx = self.builder.build_response_context(
            reasoning_result=result,
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=[],
            state=state,
            history=[],
        )
        prompt = self.builder.build_response_prompt(response_ctx)
        assert "ONE question" in prompt or "one question" in prompt.lower()
        assert "ONE" in prompt or "one step" in prompt.lower()

    def test_build_decision_prompt_contains_schema(self):
        state = self._make_state()
        ctx = self.builder.build_reasoning_context(
            user_message="VPN error",
            classification=MockClassification(),
            strategy=self.strategy_reg.get("VPN"),
            retrieved_docs=[],
            state=state,
            history=[],
        )
        prompt = self.builder.build_decision_prompt(ctx)
        assert "next_action" in prompt
        assert "confidence" in prompt
        assert "escalation" in prompt


# ═════════════════════════════════════════════════════════════════════════════
# 6. REASONING ENGINE
# ═════════════════════════════════════════════════════════════════════════════

class TestReasoningEngine:
    """Validate structured JSON output, schema validation, and fallback rules."""

    def setup_method(self):
        from app.services.reasoning_service import ReasoningEngine, NextAction
        from app.services.context_builder import ContextBuilder
        from app.services.troubleshooting_strategy import TroubleshootingStrategyRegistry
        from app.services.troubleshooting_state_service import TroubleshootingStateManager
        self.NextAction = NextAction
        self.ctx_builder = ContextBuilder()
        self.strategy_reg = TroubleshootingStrategyRegistry()
        self.state_mgr = TroubleshootingStateManager()

    def _make_engine(self, decision_json=None):
        from app.services.reasoning_service import ReasoningEngine
        provider = _make_mock_ai_provider(decision_json=decision_json)
        return ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder), provider

    def _make_context(self, category="VPN", turn_count=0, missing_ev=None, attempted=None):
        from app.services.context_builder import ReasoningContext
        sid = str(uuid.uuid4())
        state = self.state_mgr.create(sid, "VPN issue", category)
        state.turn_count = turn_count
        return self.ctx_builder.build_reasoning_context(
            user_message="My VPN keeps disconnecting",
            classification=MockClassification(category=category),
            strategy=self.strategy_reg.get(category),
            retrieved_docs=[],
            state=state,
            history=[],
        )

    def test_reason_returns_reasoning_result(self):
        from app.services.reasoning_service import ReasoningResult
        engine, _ = self._make_engine()
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert isinstance(result, ReasoningResult)

    def test_reasoning_result_has_no_response_text_field(self):
        """ReasoningResult must NEVER contain user-facing response text."""
        from app.services.reasoning_service import ReasoningResult
        import dataclasses
        field_names = {f.name for f in dataclasses.fields(ReasoningResult)}
        # These field names would indicate user-facing text leaking into reasoning
        forbidden = {"response_text", "message", "reply", "user_response"}
        assert not (field_names & forbidden), (
            f"ReasoningResult contains user-facing field(s): {field_names & forbidden}"
        )

    def test_valid_json_produces_correct_next_action(self):
        decision = _make_valid_decision(next_action="GUIDE_STEP", reason_code="KB_AVAILABLE")
        engine, _ = self._make_engine(decision_json=decision)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.next_action == self.NextAction.GUIDE_STEP
        assert result.is_fallback is False

    def test_invalid_json_triggers_fallback(self):
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = "this is not json at all"
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.is_fallback is True

    def test_missing_schema_key_triggers_fallback(self):
        """JSON missing a required key must trigger fallback."""
        incomplete = json.dumps({
            "next_action": "ASK_QUESTION",
            "confidence": 0.8,
            # missing_information missing → should fail validation
        })
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = incomplete
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.is_fallback is True

    def test_invalid_next_action_triggers_fallback(self):
        bad_action = _make_valid_decision()
        data = json.loads(bad_action)
        data["next_action"] = "DO_SOMETHING_MADE_UP"
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = json.dumps(data)
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.is_fallback is True

    def test_provider_exception_triggers_fallback(self):
        provider = _make_mock_ai_provider()
        provider.generate_response.side_effect = RuntimeError("Provider unavailable")
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.is_fallback is True
        assert result.next_action in list(self.NextAction)

    def test_fallback_escalates_after_turn_threshold(self):
        from app.services.reasoning_service import ReasoningEngine
        provider = _make_mock_ai_provider()
        provider.generate_response.side_effect = RuntimeError("fail")
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context(turn_count=9)  # > ESCALATION_TURN_THRESHOLD (8)
        result = engine.reason(ctx)
        assert result.is_fallback is True
        assert result.next_action == self.NextAction.ESCALATE

    def test_fallback_asks_question_when_missing_evidence(self):
        from app.services.reasoning_service import ReasoningEngine
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = "not json"
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        # Create a context where missing_evidence is populated
        ctx = self._make_context(turn_count=1)
        # missing_evidence should be populated by ContextBuilder for VPN with no user answers
        result = engine.reason(ctx)
        assert result.is_fallback is True
        assert result.next_action in (self.NextAction.ASK_QUESTION, self.NextAction.ESCALATE)

    def test_reasoning_raw_output_not_returned_in_response_text(self):
        """raw_reasoning is internal — result must have no response_text attribute."""
        engine, _ = self._make_engine()
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert not hasattr(result, "response_text")

    def test_confidence_clamped_to_0_1(self):
        decision = _make_valid_decision(confidence=1.5)  # out of range
        data = json.loads(decision)
        data["confidence"] = 1.5
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = json.dumps(data)
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        if not result.is_fallback:
            assert 0.0 <= result.confidence <= 1.0

    def test_markdown_fences_stripped_from_llm_output(self):
        raw = "```json\n" + _make_valid_decision() + "\n```"
        provider = _make_mock_ai_provider()
        provider.generate_response.return_value = raw
        from app.services.reasoning_service import ReasoningEngine
        engine = ReasoningEngine(ai_provider=provider, context_builder=self.ctx_builder)
        ctx = self._make_context()
        result = engine.reason(ctx)
        assert result.is_fallback is False


# ═════════════════════════════════════════════════════════════════════════════
# 7. ORCHESTRATOR — CONVERSATION FLOWS
# ═════════════════════════════════════════════════════════════════════════════

class TestOrchestratorConversationFlows:
    """End-to-end conversation flows with mocked AI provider."""

    def _flow(self, category: str, messages: List[str]) -> List[str]:
        """Run a multi-turn conversation and return all response_text values."""
        provider = _make_mock_ai_provider()
        orch = _build_orchestrator(ai_provider=provider)
        session_id = str(uuid.uuid4())
        history: List[dict] = []
        responses: List[str] = []

        for msg in messages:
            req = _make_request(
                session_id=session_id,
                user_message=msg,
                category=category,
                history=list(history),
            )
            result = orch.handle(req)
            history.append({"role": "user", "text": msg})
            history.append({"role": "model", "text": result.response_text})
            responses.append(result.response_text)

        return responses

    def test_vpn_issue_produces_response(self):
        responses = self._flow("VPN", ["My GlobalProtect VPN keeps disconnecting"])
        assert len(responses) == 1
        assert responses[0]  # non-empty

    def test_multi_turn_vpn_flow(self):
        responses = self._flow("VPN", [
            "My VPN is not connecting",
            "I see error 619",
            "I already restarted my laptop",
        ])
        assert len(responses) == 3
        for r in responses:
            assert r  # all non-empty

    def test_outlook_issue_produces_response(self):
        responses = self._flow("OUTLOOK", ["Outlook is crashing when I open it"])
        assert responses[0]

    def test_printer_issue_produces_response(self):
        responses = self._flow("PRINTER", ["My printer shows offline status"])
        assert responses[0]

    def test_sap_login_failure_flow(self):
        responses = self._flow("SAP", ["I cannot log in to SAP, error RFC_ERROR_LOGON_FAILURE"])
        assert responses[0]

    def test_password_issue_flow(self):
        responses = self._flow("PASSWORD_RESET", ["My Windows password has expired"])
        assert responses[0]

    def test_wifi_issue_flow(self):
        responses = self._flow("GUEST_WIFI", ["I cannot connect to BS-Guest Wi-Fi"])
        assert responses[0]

    def test_hardware_issue_flow(self):
        responses = self._flow("DEVICE_HEALTH", ["My laptop fan is very loud and it is slow"])
        assert responses[0]

    def test_browser_issue_flow(self):
        responses = self._flow("BROWSER", ["Edge browser crashes on our internal portal"])
        assert responses[0]

    def test_response_comes_from_ai_provider_chat(self):
        """Response must come from ai_provider.chat(), not from reasoning layer."""
        expected_response = "Can you tell me what error code you see in GlobalProtect?"
        provider = _make_mock_ai_provider(chat_response=expected_response)
        orch = _build_orchestrator(ai_provider=provider)
        req = _make_request(user_message="VPN not connecting")
        result = orch.handle(req)
        assert result.response_text == expected_response

    def test_response_does_not_contain_kb_article_ids(self):
        """The final response must not contain raw KB article IDs like 'KB0001'."""
        # The chat() response is controlled by mock — the orchestrator must not
        # inject KB article IDs into it
        provider = _make_mock_ai_provider(
            chat_response="Could you restart your VPN client and try again?"
        )
        orch = _build_orchestrator(ai_provider=provider)
        req = _make_request(user_message="VPN error")
        result = orch.handle(req)
        import re
        kb_pattern = re.compile(r'\bKB\d{4,}\b')
        assert not kb_pattern.search(result.response_text), (
            f"Response contains raw KB article ID: {result.response_text}"
        )


# ═════════════════════════════════════════════════════════════════════════════
# 8. ORCHESTRATOR — STATE PERSISTENCE
# ═════════════════════════════════════════════════════════════════════════════

class TestOrchestratorStatePersistence:

    def test_state_persists_across_turns(self):
        """State after turn N must be available at the start of turn N+1."""
        provider = _make_mock_ai_provider()
        orch = _build_orchestrator(ai_provider=provider)
        sid = str(uuid.uuid4())

        req1 = _make_request(session_id=sid, user_message="VPN not connecting")
        result1 = orch.handle(req1)
        assert result1.state.turn_count == 1

        req2 = _make_request(session_id=sid, user_message="Error 619")
        result2 = orch.handle(req2)
        assert result2.state.turn_count == 2

    def test_same_session_id_uses_same_state(self):
        """Two requests with the same session_id share state."""
        provider = _make_mock_ai_provider()
        orch = _build_orchestrator(ai_provider=provider)
        sid = str(uuid.uuid4())

        orch.handle(_make_request(session_id=sid, user_message="VPN not working"))
        orch.handle(_make_request(session_id=sid, user_message="Still broken"))

        from app.services.troubleshooting_state_service import TroubleshootingStateManager
        # Access state manager through orchestrator's attribute
        state = orch._state_manager.get(sid)
        assert state is not None
        assert state.turn_count == 2

    def test_different_sessions_have_independent_state(self):
        provider = _make_mock_ai_provider()
        orch = _build_orchestrator(ai_provider=provider)
        sid1 = str(uuid.uuid4())
        sid2 = str(uuid.uuid4())

        orch.handle(_make_request(session_id=sid1, user_message="VPN issue"))
        orch.handle(_make_request(session_id=sid2, user_message="Printer issue"))

        s1 = orch._state_manager.get(sid1)
        s2 = orch._state_manager.get(sid2)
        assert s1.session_id != s2.session_id

    def test_completed_steps_never_repeated(self):
        """Steps in state.attempted_actions must not be re-guided."""
        decision_guide = _make_valid_decision(
            next_action="GUIDE_STEP",
            selected_step="Restart VPN client",
            reason_code="KB_AVAILABLE",
        )
        provider = _make_mock_ai_provider(decision_json=decision_guide)
        orch = _build_orchestrator(ai_provider=provider)
        sid = str(uuid.uuid4())

        # Turn 1 — guides "Restart VPN client"
        orch.handle(_make_request(session_id=sid, user_message="VPN disconnecting"))

        state = orch._state_manager.get(sid)
        assert orch._state_manager.has_attempted(state, "Restart VPN client") is True


# ═════════════════════════════════════════════════════════════════════════════
# 9. ORCHESTRATOR — RESOLUTION
# ═════════════════════════════════════════════════════════════════════════════

class TestOrchestratorResolution:

    def test_resolve_action_marks_is_resolved(self):
        decision = _make_valid_decision(next_action="RESOLVE", reason_code="USER_CONFIRMED")
        provider = _make_mock_ai_provider(decision_json=decision)
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="VPN works now"))
        assert result.is_resolved is True

    def test_resolve_action_sets_resolution_status(self):
        from app.services.troubleshooting_state_service import ResolutionStatus
        decision = _make_valid_decision(next_action="RESOLVE", reason_code="USER_CONFIRMED")
        provider = _make_mock_ai_provider(decision_json=decision)
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="It works"))
        assert result.state.resolution_status == ResolutionStatus.RESOLVED

    def test_non_resolve_action_leaves_unresolved(self):
        from app.services.troubleshooting_state_service import ResolutionStatus
        decision = _make_valid_decision(next_action="ASK_QUESTION")
        provider = _make_mock_ai_provider(decision_json=decision)
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="VPN not working"))
        assert result.is_resolved is False
        assert result.state.resolution_status == ResolutionStatus.UNRESOLVED


# ═════════════════════════════════════════════════════════════════════════════
# 10. ORCHESTRATOR — ESCALATION
# ═════════════════════════════════════════════════════════════════════════════

class TestOrchestratorEscalation:

    def test_escalate_action_sets_requires_escalation(self):
        decision = _make_valid_decision(
            next_action="ESCALATE", escalation=True, reason_code="STEPS_EXHAUSTED"
        )
        provider = _make_mock_ai_provider(decision_json=decision)
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="Nothing works"))
        assert result.requires_escalation is True

    def test_escalate_passes_session_id_to_ticket_service(self):
        decision = _make_valid_decision(next_action="ESCALATE", escalation=True)
        provider = _make_mock_ai_provider(decision_json=decision)
        ticket_service = MagicMock()
        orch = _build_orchestrator(ai_provider=provider, ticket_service=ticket_service)
        sid = str(uuid.uuid4())
        orch.handle(_make_request(session_id=sid, user_message="Escalate please"))

        # TicketService.create_ticket must have been called
        assert ticket_service.create_ticket.called

    def test_escalation_context_contains_conversation_history(self):
        decision = _make_valid_decision(next_action="ESCALATE", escalation=True)
        provider = _make_mock_ai_provider(decision_json=decision)
        ticket_service = MagicMock()
        orch = _build_orchestrator(ai_provider=provider, ticket_service=ticket_service)

        history = [
            {"role": "user",  "text": "My VPN is broken"},
            {"role": "model", "text": "Let me check the error code"},
        ]
        orch.handle(_make_request(user_message="Escalate", history=history))

        call_kwargs = ticket_service.create_ticket.call_args
        assert call_kwargs is not None
        # The context kwarg should include conversation history
        ctx_arg = call_kwargs.kwargs.get("context") or (call_kwargs.args[2] if len(call_kwargs.args) > 2 else None)
        if ctx_arg:
            assert "conversation_history" in ctx_arg

    def test_escalation_context_contains_session_id(self):
        decision = _make_valid_decision(next_action="ESCALATE", escalation=True)
        provider = _make_mock_ai_provider(decision_json=decision)
        ticket_service = MagicMock()
        orch = _build_orchestrator(ai_provider=provider, ticket_service=ticket_service)
        sid = str(uuid.uuid4())
        orch.handle(_make_request(session_id=sid))
        result_with_ctx = orch.handle(_make_request(session_id=str(uuid.uuid4())))
        assert result_with_ctx.escalation_context is not None or result_with_ctx.requires_escalation is True

    def test_escalate_marks_state_as_escalated(self):
        from app.services.troubleshooting_state_service import ResolutionStatus
        decision = _make_valid_decision(next_action="ESCALATE", escalation=True)
        provider = _make_mock_ai_provider(decision_json=decision)
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="Please escalate"))
        assert result.state.resolution_status == ResolutionStatus.ESCALATED

    def test_orchestrator_does_not_crash_if_ticket_service_raises(self):
        """Escalation failure must not propagate as an exception to the caller."""
        decision = _make_valid_decision(next_action="ESCALATE", escalation=True)
        provider = _make_mock_ai_provider(decision_json=decision)
        ticket_service = MagicMock()
        ticket_service.create_ticket.side_effect = RuntimeError("ServiceNow unavailable")
        orch = _build_orchestrator(ai_provider=provider, ticket_service=ticket_service)
        # Must not raise
        result = orch.handle(_make_request(user_message="Escalate please"))
        assert result is not None


# ═════════════════════════════════════════════════════════════════════════════
# 11. ORCHESTRATOR — ERROR RESILIENCE
# ═════════════════════════════════════════════════════════════════════════════

class TestOrchestratorErrorResilience:

    def test_ai_provider_chat_failure_returns_fallback(self):
        """If ai_provider.chat() raises, orchestrator must return fallback response."""
        provider = _make_mock_ai_provider()
        provider.chat.side_effect = RuntimeError("Gemini unavailable")
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="VPN broken"))
        assert result is not None
        assert result.response_text  # fallback message is non-empty

    def test_ai_provider_error_prefix_returns_fallback(self):
        """If chat() returns [AI Provider Error] prefix, return fallback."""
        provider = _make_mock_ai_provider(
            chat_response="[AI Provider Error] Rate limit exceeded"
        )
        orch = _build_orchestrator(ai_provider=provider)
        result = orch.handle(_make_request(user_message="VPN broken"))
        # Should not expose the error prefix to users
        assert not result.response_text.startswith("[AI Provider Error]")

    def test_orchestrator_never_raises(self):
        """handle() must never raise — all errors produce a result."""
        provider = _make_mock_ai_provider()
        provider.generate_response.side_effect = Exception("Catastrophic failure")
        provider.chat.side_effect = Exception("Chat failure")
        orch = _build_orchestrator(ai_provider=provider)
        # Should not raise
        result = orch.handle(_make_request(user_message="Help"))
        assert result is not None
